spring:
  datasource:
    url: jdbc:mysql://localhost:3307/customer_service
    username: customer_user
    password: customer_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}"

product-service:
  product-service-url: http://localhost:8080